language: node_js

node_js:
 - 6.0.0

integrations:
  notifications:
    - integrationName: MUSIT-Slack
      type: slack
      recipients:
        - "#travis-builds"
      on_success: always
      on_failure: always

branches:
  only:
    - master

build:
  pre_ci_boot:
    image_name: jarlah/node-shippable
    image_tag: latest
    pull: true
    options: "-e HOME=/root"
  ci:
    - npm -v
    - node -v
    - npm install
    - npm run deploy:dev
    - npm run deploy:prod
#  on_success:
#    - npm run codecov
