language: node_js

node_js:
 - 6.0.0
 
integrations:
  notifications:
    - integrationName: MUSIT-Slack
      type: slack
      recipients:
        - "#travis-builds"

build:
  ci:
   - npm install --force
   - npm run lint
   - npm run test:coverage
   - npm run build
