language: node_js

node_js:
 - 6.7.0

env:
  global:
    - secure: O3oq63NAtJVGTkS3c+369X4g7WOSQiLIyf0TPK3jyeLAG60PU8nzZK4LRfYM8KVl6wFaZ/2tpbFOOUZsQRmZsncM4p8WvXenvUvyyf1upVNG2gUXwhRo6xlZdLJBvv+JX4ttHuqPYvYg67X3k9Ke8KoYhib8yi/wbAHgysQD0Tu8fux9AZ/CsZ9kkg80ThlUW3QLjFmKQ8C90nzJYTc5mmOpjWlYEfLvTjFdjXBjhJENtwtAV1MmARcDKL6efqbte9IrCNB+moPuKVMtbMQoCjIMWYJ9UHdW84hZ+NMQzO31IeUYiS2TZRtGoNgBvC3YstWs4JbZg8QYCky+5sQuNA==

integrations:
  notifications:
    - integrationName: MUSIT-Slack
      type: slack
      recipients:
        - "#travis-builds"
      on_success: always
      on_failure: always

branches:
  only:
    - master

build:
  cache: true
  cache_dir_list:
    - $SHIPPABLE_BUILD_DIR/node_modules
    - $SHIPPABLE_BUILD_DIR/.git
  ci:
   - npm install
   - npm run lint
   - npm run flow
   - npm test -- --coverage --collectCoverageFrom='src/**/*.{js,jsx}'
   - npm run codacy
   - npm run build
