// flow-typed signature: d3911416ecd3b5fb6ecbb097aee36f32
// flow-typed version: <<STUB>>/jest-enzyme_v^3.2.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-enzyme'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-enzyme' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-enzyme/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-enzyme/lib/index.js' {
  declare module.exports: $Exports<'jest-enzyme/lib/index'>;
}
