// flow-typed signature: 46c2cccfab22e4255b066a1dd6b315ff
// flow-typed version: <<STUB>>/node-localstorage_v^1.3.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-localstorage'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-localstorage' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-localstorage/LocalStorage' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-localstorage/LocalStorage.js' {
  declare module.exports: $Exports<'node-localstorage/LocalStorage'>;
}
