// flow-typed signature: 04d73c9c8e031b6703fd5ac3731eaebe
// flow-typed version: <<STUB>>/react-loader_v^2.4.2/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-loader/examples/create-react-app/src/BasicExample' {
  declare module.exports: any;
}

declare module 'react-loader/examples/create-react-app/src/index' {
  declare module.exports: any;
}

declare module 'react-loader/lib/react-loader' {
  declare module.exports: any;
}

declare module 'react-loader/lib/react-loader' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-loader/examples/create-react-app/src/BasicExample.js' {
  declare module.exports: $Exports<'react-loader/examples/create-react-app/src/BasicExample'>;
}
declare module 'react-loader/examples/create-react-app/src/index.js' {
  declare module.exports: $Exports<'react-loader/examples/create-react-app/src/index'>;
}
declare module 'react-loader/lib/react-loader.js' {
  declare module.exports: $Exports<'react-loader/lib/react-loader'>;
}
declare module 'react-loader/lib/react-loader.jsx' {
  declare module.exports: $Exports<'react-loader/lib/react-loader'>;
}
