// flow-typed signature: 10bcf2d6b943e39ffec218afebccfecf
// flow-typed version: <<STUB>>/react-i18nify_v^1.8.7/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-i18nify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-i18nify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-i18nify/build/index' {
  declare module.exports: any;
}

declare module 'react-i18nify/build/lib/Base' {
  declare module.exports: any;
}

declare module 'react-i18nify/build/lib/formatMissingTranslation' {
  declare module.exports: any;
}

declare module 'react-i18nify/build/lib/I18n' {
  declare module.exports: any;
}

declare module 'react-i18nify/build/lib/Localize' {
  declare module.exports: any;
}

declare module 'react-i18nify/build/lib/Translate' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-i18nify/build/index.js' {
  declare module.exports: $Exports<'react-i18nify/build/index'>;
}
declare module 'react-i18nify/build/lib/Base.js' {
  declare module.exports: $Exports<'react-i18nify/build/lib/Base'>;
}
declare module 'react-i18nify/build/lib/formatMissingTranslation.js' {
  declare module.exports: $Exports<'react-i18nify/build/lib/formatMissingTranslation'>;
}
declare module 'react-i18nify/build/lib/I18n.js' {
  declare module.exports: $Exports<'react-i18nify/build/lib/I18n'>;
}
declare module 'react-i18nify/build/lib/Localize.js' {
  declare module.exports: $Exports<'react-i18nify/build/lib/Localize'>;
}
declare module 'react-i18nify/build/lib/Translate.js' {
  declare module.exports: $Exports<'react-i18nify/build/lib/Translate'>;
}
