// flow-typed signature: de65d70beb96480dd4ea2a60798ee2ee
// flow-typed version: <<STUB>>/react-rxjs_vhttps://gitlab.com/MUSIT-Norway/react-rxjs.git#v2.0.3/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-rxjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-rxjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-rxjs/dist/index' {
  declare module.exports: any;
}

declare module 'react-rxjs/dist/RxContainer' {
  declare module.exports: any;
}

declare module 'react-rxjs/dist/RxInject' {
  declare module.exports: any;
}

declare module 'react-rxjs/dist/RxProvide' {
  declare module.exports: any;
}

declare module 'react-rxjs/dist/RxStore' {
  declare module.exports: any;
}

declare module 'react-rxjs/src/RxContainer' {
  declare module.exports: any;
}

declare module 'react-rxjs/src/RxInject' {
  declare module.exports: any;
}

declare module 'react-rxjs/src/RxProvide' {
  declare module.exports: any;
}

declare module 'react-rxjs/src/RxStore' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-rxjs/dist/index.js' {
  declare module.exports: $Exports<'react-rxjs/dist/index'>;
}
declare module 'react-rxjs/dist/RxContainer.js' {
  declare module.exports: $Exports<'react-rxjs/dist/RxContainer'>;
}
declare module 'react-rxjs/dist/RxInject.js' {
  declare module.exports: $Exports<'react-rxjs/dist/RxInject'>;
}
declare module 'react-rxjs/dist/RxProvide.js' {
  declare module.exports: $Exports<'react-rxjs/dist/RxProvide'>;
}
declare module 'react-rxjs/dist/RxStore.js' {
  declare module.exports: $Exports<'react-rxjs/dist/RxStore'>;
}
declare module 'react-rxjs/src/RxContainer.js' {
  declare module.exports: $Exports<'react-rxjs/src/RxContainer'>;
}
declare module 'react-rxjs/src/RxInject.js' {
  declare module.exports: $Exports<'react-rxjs/src/RxInject'>;
}
declare module 'react-rxjs/src/RxProvide.js' {
  declare module.exports: $Exports<'react-rxjs/src/RxProvide'>;
}
declare module 'react-rxjs/src/RxStore.js' {
  declare module.exports: $Exports<'react-rxjs/src/RxStore'>;
}
