// flow-typed signature: 3b53b7a1ae245bcac09de857c1620808
// flow-typed version: <<STUB>>/react-router-bootstrap_v0.24.3/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-router-bootstrap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-router-bootstrap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-router-bootstrap/lib/index' {
  declare module.exports: any;
}

declare module 'react-router-bootstrap/lib/IndexLinkContainer' {
  declare module.exports: any;
}

declare module 'react-router-bootstrap/lib/LinkContainer' {
  declare module.exports: any;
}

declare module 'react-router-bootstrap/lib/ReactRouterBootstrap' {
  declare module.exports: any;
}

declare module 'react-router-bootstrap/lib/ReactRouterBootstrap.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-router-bootstrap/lib/index.js' {
  declare module.exports: $Exports<'react-router-bootstrap/lib/index'>;
}
declare module 'react-router-bootstrap/lib/IndexLinkContainer.js' {
  declare module.exports: $Exports<'react-router-bootstrap/lib/IndexLinkContainer'>;
}
declare module 'react-router-bootstrap/lib/LinkContainer.js' {
  declare module.exports: $Exports<'react-router-bootstrap/lib/LinkContainer'>;
}
declare module 'react-router-bootstrap/lib/ReactRouterBootstrap.js' {
  declare module.exports: $Exports<'react-router-bootstrap/lib/ReactRouterBootstrap'>;
}
declare module 'react-router-bootstrap/lib/ReactRouterBootstrap.min.js' {
  declare module.exports: $Exports<'react-router-bootstrap/lib/ReactRouterBootstrap.min'>;
}
